version: '2.32.4'
services:
  addition:
    build: ./addition
    ports:
      - "5001:5001"
  subtraction:
    build: ./subtraction
    ports:
      - "5002:5002"
  multiplication:
    build: ./multiplication
    ports:
      - "5003:5003"
  division:
    build: ./division
    ports:
      - "5004:5004"